<template>
    <MainLayout>
        <div class="h-[122px] w-full bg-[#848484] items-center justify-center align-center flex">
            <p class="text-center text-white text-[26px] md:text-[52px]">Nuestras Noticias</p>
        </div>
        <div class="border-b-[5px] rounded border-divider-title max-w-[1200px] mx-auto py-1"></div>

        <div>
            <NoticiaComponent 
            url-main-img="https://s3-alpha-sig.figma.com/img/b6be/f661/7917a695fd372aeb0d7e781a58bc2225?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Bh5kUdw1HTugBcRT50O-bCRULNlOweA5fsjWKdnzeO~m2aDH1aPxw0Hphl~Hh83vnIn6hq2w-fgkoxKTfNVQ4JN6jyAtmRzrwbVhE5xdm0fILjl2oxuTYFGsBkDpKptj6VaZ7DkAUVnCvNXNtxjsMlo-ZqPX0wg-ZVERLqOk8VTr-36ZnanZ3W9rgak6R4jqUOQvIyiSUOAH4RD990wpdsUglpXRYpU4Hyx61-c66fw4lJLHDmpNq-WZNu55Ub8KktWWwi~w96GfbX0UAW2wn9VfraX6qi4wzYz-P-I-4m6eltsBq2U~t50QaEp0IVit6bxjyQ421gzPRR459nBIuA__"
            url-sub-img="https://s3-alpha-sig.figma.com/img/5b17/a6f9/156a755f626fdae642d87a5b1a6d6c92?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=cMA3THl3yN5RvVKgDYDsvsZM~wHasb1Tcnq1RsPrzzcPAvJWJ21SHx4QLX3w0uRTa7De0QCS0JCT2Ub99emKOaWxg3GOikhIB6qkw1bc8ikbBcsHG6CFqIjB-Yt39huQ1qZiTv-LGCTKdVhcEnDZeYDkNj6a96KqivQB3oVgiq5WvZHAQTEk5OTM0VYqbx9amntXbyCRGd6Wd2nm-mKpvGVpD2OFuWR0il29rtt8g3wzWJteBTjKDpujt5Cj8L1QhmEYKkt6rqTi6J6YXgcyDPjvRb11vZKUFYtOlJz9T4rko-QngA5qFgBNv223aLCUMwAq1NVjpG8uwt~chz-6Hw__"
            title="Evento cierre de proyecto Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales"
            content="La Pontificia Universidad Católica de Ibarra (PUCE-I), contribuye en la innovación educativa para la gestión empresarial en el contexto latinoamericano. Dentro del proyecto “Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales” se materializa a través del empleo del METAVERSO, una de las tecnologías digitales de tendencia y expectativa global, que consiste en el uso de una plataforma digital accesible a través de las gafas de realidad virtual e Internet. Un equipo de docentes conformado por: Maricela Ormaza, María José Dávila y José Luis Ibarra, aseguran que las posibilidades del aprovechamiento de las tecnologías digitales de última generación en el ámbito universitario son infinitas, apostando por proporcionar al estudiante el acceso a nuevas y mejores experiencias educativas bien direccionadas, promoviendo en los alumnos las competencias profesionales, la libertad de pensamiento, la reflexión crítica y el compromiso ético."
            author="Maricela Ormaza"
            />
            <NoticiaComponent 
            url-main-img="https://s3-alpha-sig.figma.com/img/b6be/f661/7917a695fd372aeb0d7e781a58bc2225?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Bh5kUdw1HTugBcRT50O-bCRULNlOweA5fsjWKdnzeO~m2aDH1aPxw0Hphl~Hh83vnIn6hq2w-fgkoxKTfNVQ4JN6jyAtmRzrwbVhE5xdm0fILjl2oxuTYFGsBkDpKptj6VaZ7DkAUVnCvNXNtxjsMlo-ZqPX0wg-ZVERLqOk8VTr-36ZnanZ3W9rgak6R4jqUOQvIyiSUOAH4RD990wpdsUglpXRYpU4Hyx61-c66fw4lJLHDmpNq-WZNu55Ub8KktWWwi~w96GfbX0UAW2wn9VfraX6qi4wzYz-P-I-4m6eltsBq2U~t50QaEp0IVit6bxjyQ421gzPRR459nBIuA__"
            url-sub-img="https://s3-alpha-sig.figma.com/img/5b17/a6f9/156a755f626fdae642d87a5b1a6d6c92?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=cMA3THl3yN5RvVKgDYDsvsZM~wHasb1Tcnq1RsPrzzcPAvJWJ21SHx4QLX3w0uRTa7De0QCS0JCT2Ub99emKOaWxg3GOikhIB6qkw1bc8ikbBcsHG6CFqIjB-Yt39huQ1qZiTv-LGCTKdVhcEnDZeYDkNj6a96KqivQB3oVgiq5WvZHAQTEk5OTM0VYqbx9amntXbyCRGd6Wd2nm-mKpvGVpD2OFuWR0il29rtt8g3wzWJteBTjKDpujt5Cj8L1QhmEYKkt6rqTi6J6YXgcyDPjvRb11vZKUFYtOlJz9T4rko-QngA5qFgBNv223aLCUMwAq1NVjpG8uwt~chz-6Hw__"
            title="Evento cierre de proyecto Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales"
            content="La Pontificia Universidad Católica de Ibarra (PUCE-I), contribuye en la innovación educativa para la gestión empresarial en el contexto latinoamericano. Dentro del proyecto “Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales” se materializa a través del empleo del METAVERSO, una de las tecnologías digitales de tendencia y expectativa global, que consiste en el uso de una plataforma digital accesible a través de las gafas de realidad virtual e Internet. Un equipo de docentes conformado por: Maricela Ormaza, María José Dávila y José Luis Ibarra, aseguran que las posibilidades del aprovechamiento de las tecnologías digitales de última generación en el ámbito universitario son infinitas, apostando por proporcionar al estudiante el acceso a nuevas y mejores experiencias educativas bien direccionadas, promoviendo en los alumnos las competencias profesionales, la libertad de pensamiento, la reflexión crítica y el compromiso ético."
            author="Maricela Ormaza"
            />
            <NoticiaComponent 
            url-main-img="https://s3-alpha-sig.figma.com/img/b6be/f661/7917a695fd372aeb0d7e781a58bc2225?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Bh5kUdw1HTugBcRT50O-bCRULNlOweA5fsjWKdnzeO~m2aDH1aPxw0Hphl~Hh83vnIn6hq2w-fgkoxKTfNVQ4JN6jyAtmRzrwbVhE5xdm0fILjl2oxuTYFGsBkDpKptj6VaZ7DkAUVnCvNXNtxjsMlo-ZqPX0wg-ZVERLqOk8VTr-36ZnanZ3W9rgak6R4jqUOQvIyiSUOAH4RD990wpdsUglpXRYpU4Hyx61-c66fw4lJLHDmpNq-WZNu55Ub8KktWWwi~w96GfbX0UAW2wn9VfraX6qi4wzYz-P-I-4m6eltsBq2U~t50QaEp0IVit6bxjyQ421gzPRR459nBIuA__"
            url-sub-img="https://s3-alpha-sig.figma.com/img/5b17/a6f9/156a755f626fdae642d87a5b1a6d6c92?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=cMA3THl3yN5RvVKgDYDsvsZM~wHasb1Tcnq1RsPrzzcPAvJWJ21SHx4QLX3w0uRTa7De0QCS0JCT2Ub99emKOaWxg3GOikhIB6qkw1bc8ikbBcsHG6CFqIjB-Yt39huQ1qZiTv-LGCTKdVhcEnDZeYDkNj6a96KqivQB3oVgiq5WvZHAQTEk5OTM0VYqbx9amntXbyCRGd6Wd2nm-mKpvGVpD2OFuWR0il29rtt8g3wzWJteBTjKDpujt5Cj8L1QhmEYKkt6rqTi6J6YXgcyDPjvRb11vZKUFYtOlJz9T4rko-QngA5qFgBNv223aLCUMwAq1NVjpG8uwt~chz-6Hw__"
            title="Evento cierre de proyecto Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales"
            content="La Pontificia Universidad Católica de Ibarra (PUCE-I), contribuye en la innovación educativa para la gestión empresarial en el contexto latinoamericano. Dentro del proyecto “Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales” se materializa a través del empleo del METAVERSO, una de las tecnologías digitales de tendencia y expectativa global, que consiste en el uso de una plataforma digital accesible a través de las gafas de realidad virtual e Internet. Un equipo de docentes conformado por: Maricela Ormaza, María José Dávila y José Luis Ibarra, aseguran que las posibilidades del aprovechamiento de las tecnologías digitales de última generación en el ámbito universitario son infinitas, apostando por proporcionar al estudiante el acceso a nuevas y mejores experiencias educativas bien direccionadas, promoviendo en los alumnos las competencias profesionales, la libertad de pensamiento, la reflexión crítica y el compromiso ético."
            author="Maricela Ormaza"
            />
            <NoticiaComponent 
            url-main-img="https://s3-alpha-sig.figma.com/img/b6be/f661/7917a695fd372aeb0d7e781a58bc2225?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Bh5kUdw1HTugBcRT50O-bCRULNlOweA5fsjWKdnzeO~m2aDH1aPxw0Hphl~Hh83vnIn6hq2w-fgkoxKTfNVQ4JN6jyAtmRzrwbVhE5xdm0fILjl2oxuTYFGsBkDpKptj6VaZ7DkAUVnCvNXNtxjsMlo-ZqPX0wg-ZVERLqOk8VTr-36ZnanZ3W9rgak6R4jqUOQvIyiSUOAH4RD990wpdsUglpXRYpU4Hyx61-c66fw4lJLHDmpNq-WZNu55Ub8KktWWwi~w96GfbX0UAW2wn9VfraX6qi4wzYz-P-I-4m6eltsBq2U~t50QaEp0IVit6bxjyQ421gzPRR459nBIuA__"
            url-sub-img="https://s3-alpha-sig.figma.com/img/5b17/a6f9/156a755f626fdae642d87a5b1a6d6c92?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=cMA3THl3yN5RvVKgDYDsvsZM~wHasb1Tcnq1RsPrzzcPAvJWJ21SHx4QLX3w0uRTa7De0QCS0JCT2Ub99emKOaWxg3GOikhIB6qkw1bc8ikbBcsHG6CFqIjB-Yt39huQ1qZiTv-LGCTKdVhcEnDZeYDkNj6a96KqivQB3oVgiq5WvZHAQTEk5OTM0VYqbx9amntXbyCRGd6Wd2nm-mKpvGVpD2OFuWR0il29rtt8g3wzWJteBTjKDpujt5Cj8L1QhmEYKkt6rqTi6J6YXgcyDPjvRb11vZKUFYtOlJz9T4rko-QngA5qFgBNv223aLCUMwAq1NVjpG8uwt~chz-6Hw__"
            title="Evento cierre de proyecto Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales"
            content="La Pontificia Universidad Católica de Ibarra (PUCE-I), contribuye en la innovación educativa para la gestión empresarial en el contexto latinoamericano. Dentro del proyecto “Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales” se materializa a través del empleo del METAVERSO, una de las tecnologías digitales de tendencia y expectativa global, que consiste en el uso de una plataforma digital accesible a través de las gafas de realidad virtual e Internet. Un equipo de docentes conformado por: Maricela Ormaza, María José Dávila y José Luis Ibarra, aseguran que las posibilidades del aprovechamiento de las tecnologías digitales de última generación en el ámbito universitario son infinitas, apostando por proporcionar al estudiante el acceso a nuevas y mejores experiencias educativas bien direccionadas, promoviendo en los alumnos las competencias profesionales, la libertad de pensamiento, la reflexión crítica y el compromiso ético."
            author="Maricela Ormaza"
            />
            <NoticiaComponent 
            url-main-img="https://s3-alpha-sig.figma.com/img/b6be/f661/7917a695fd372aeb0d7e781a58bc2225?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Bh5kUdw1HTugBcRT50O-bCRULNlOweA5fsjWKdnzeO~m2aDH1aPxw0Hphl~Hh83vnIn6hq2w-fgkoxKTfNVQ4JN6jyAtmRzrwbVhE5xdm0fILjl2oxuTYFGsBkDpKptj6VaZ7DkAUVnCvNXNtxjsMlo-ZqPX0wg-ZVERLqOk8VTr-36ZnanZ3W9rgak6R4jqUOQvIyiSUOAH4RD990wpdsUglpXRYpU4Hyx61-c66fw4lJLHDmpNq-WZNu55Ub8KktWWwi~w96GfbX0UAW2wn9VfraX6qi4wzYz-P-I-4m6eltsBq2U~t50QaEp0IVit6bxjyQ421gzPRR459nBIuA__"
            url-sub-img="https://s3-alpha-sig.figma.com/img/5b17/a6f9/156a755f626fdae642d87a5b1a6d6c92?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=cMA3THl3yN5RvVKgDYDsvsZM~wHasb1Tcnq1RsPrzzcPAvJWJ21SHx4QLX3w0uRTa7De0QCS0JCT2Ub99emKOaWxg3GOikhIB6qkw1bc8ikbBcsHG6CFqIjB-Yt39huQ1qZiTv-LGCTKdVhcEnDZeYDkNj6a96KqivQB3oVgiq5WvZHAQTEk5OTM0VYqbx9amntXbyCRGd6Wd2nm-mKpvGVpD2OFuWR0il29rtt8g3wzWJteBTjKDpujt5Cj8L1QhmEYKkt6rqTi6J6YXgcyDPjvRb11vZKUFYtOlJz9T4rko-QngA5qFgBNv223aLCUMwAq1NVjpG8uwt~chz-6Hw__"
            title="Evento cierre de proyecto Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales"
            content="La Pontificia Universidad Católica de Ibarra (PUCE-I), contribuye en la innovación educativa para la gestión empresarial en el contexto latinoamericano. Dentro del proyecto “Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales” se materializa a través del empleo del METAVERSO, una de las tecnologías digitales de tendencia y expectativa global, que consiste en el uso de una plataforma digital accesible a través de las gafas de realidad virtual e Internet. Un equipo de docentes conformado por: Maricela Ormaza, María José Dávila y José Luis Ibarra, aseguran que las posibilidades del aprovechamiento de las tecnologías digitales de última generación en el ámbito universitario son infinitas, apostando por proporcionar al estudiante el acceso a nuevas y mejores experiencias educativas bien direccionadas, promoviendo en los alumnos las competencias profesionales, la libertad de pensamiento, la reflexión crítica y el compromiso ético."
            author="Maricela Ormaza"
            />
            <NoticiaComponent 
            url-main-img="https://s3-alpha-sig.figma.com/img/b6be/f661/7917a695fd372aeb0d7e781a58bc2225?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Bh5kUdw1HTugBcRT50O-bCRULNlOweA5fsjWKdnzeO~m2aDH1aPxw0Hphl~Hh83vnIn6hq2w-fgkoxKTfNVQ4JN6jyAtmRzrwbVhE5xdm0fILjl2oxuTYFGsBkDpKptj6VaZ7DkAUVnCvNXNtxjsMlo-ZqPX0wg-ZVERLqOk8VTr-36ZnanZ3W9rgak6R4jqUOQvIyiSUOAH4RD990wpdsUglpXRYpU4Hyx61-c66fw4lJLHDmpNq-WZNu55Ub8KktWWwi~w96GfbX0UAW2wn9VfraX6qi4wzYz-P-I-4m6eltsBq2U~t50QaEp0IVit6bxjyQ421gzPRR459nBIuA__"
            url-sub-img="https://s3-alpha-sig.figma.com/img/5b17/a6f9/156a755f626fdae642d87a5b1a6d6c92?Expires=1715558400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=cMA3THl3yN5RvVKgDYDsvsZM~wHasb1Tcnq1RsPrzzcPAvJWJ21SHx4QLX3w0uRTa7De0QCS0JCT2Ub99emKOaWxg3GOikhIB6qkw1bc8ikbBcsHG6CFqIjB-Yt39huQ1qZiTv-LGCTKdVhcEnDZeYDkNj6a96KqivQB3oVgiq5WvZHAQTEk5OTM0VYqbx9amntXbyCRGd6Wd2nm-mKpvGVpD2OFuWR0il29rtt8g3wzWJteBTjKDpujt5Cj8L1QhmEYKkt6rqTi6J6YXgcyDPjvRb11vZKUFYtOlJz9T4rko-QngA5qFgBNv223aLCUMwAq1NVjpG8uwt~chz-6Hw__"
            title="Evento cierre de proyecto Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales"
            content="La Pontificia Universidad Católica de Ibarra (PUCE-I), contribuye en la innovación educativa para la gestión empresarial en el contexto latinoamericano. Dentro del proyecto “Ambiente virtual de aprendizaje (AVA) para la toma de decisiones empresariales” se materializa a través del empleo del METAVERSO, una de las tecnologías digitales de tendencia y expectativa global, que consiste en el uso de una plataforma digital accesible a través de las gafas de realidad virtual e Internet. Un equipo de docentes conformado por: Maricela Ormaza, María José Dávila y José Luis Ibarra, aseguran que las posibilidades del aprovechamiento de las tecnologías digitales de última generación en el ámbito universitario son infinitas, apostando por proporcionar al estudiante el acceso a nuevas y mejores experiencias educativas bien direccionadas, promoviendo en los alumnos las competencias profesionales, la libertad de pensamiento, la reflexión crítica y el compromiso ético."
            author="Maricela Ormaza"
            />
        </div>

    </MainLayout>
</template>

<script setup lang="ts">
import MainLayout from '../layouts/MainLayout.vue';
import NoticiaComponent from '../components/NoticiaComponent.vue';
</script>

<style scoped></style>